# SPDX-License-Identifier: GPL-2.0
# obj-$(CONFIG_RPMSG)		+= rpmsg_core.o
# obj-$(CONFIG_RPMSG_CHAR)	+= rpmsg_char.o
# obj-$(CONFIG_RPMSG_QCOM_GLINK_RPM) += qcom_glink_rpm.o
# obj-$(CONFIG_RPMSG_QCOM_GLINK_NATIVE) += qcom_glink_native.o
# obj-$(CONFIG_RPMSG_QCOM_GLINK_SMEM) += qcom_glink_smem.o
# obj-$(CONFIG_RPMSG_QCOM_SMD)	+= qcom_smd.o
# obj-$(CONFIG_RPMSG_TTY)	+= rpmsg_tty.o
# obj-$(CONFIG_RPMSG_VIRTIO)	+= virtio_rpmsg_bus.o
obj-y		+= rpmsg_core.o
obj-y	+= rpmsg_char.o
obj-y += qcom_glink_rpm.o
obj-y += qcom_glink_native.o
# obj-y += qcom_glink_smem.o
# obj-y	+= qcom_smd.o
obj-y	+= rpmsg_tty.o
obj-y	+= virtio_rpmsg_bus.o
